### ISSUE TITLE
Variantes de las placas Lite y RevC con sockets para drivers tipo StepStick en vez de integrados en placa 

### ISSUE THREAD

**Issue by sl1pkn07** [bricogeek/bricolemon#4]
Buenas

habéis manejado la posibilidad de sacar sendas tarjetas tipo Lite o la RevC con sockets tipo StepStick (tipico Pololu intercambiable)?

para poner el derive que se desee, en el tipo de conexión que se desee (UART para los TMC2208, TMC2209, SPI para los TMC2130, TMC5160 (este creo que se puede tanto uart como SPI), etc, o en modo directo (DIR) como los DRV8825, A4988, etc) , y también fácil reemplazo si se rompe? (no tener que comprar una placa nueva)

saludos

**Comment by bricogeek** [comment]
Hola,
Actualmente no lo tenemos contemplado, ya que eso conlleva a mayor tasa de error al poner los drivers. No te puede imaginar la cantidad de placas rotas por conectar mal los drivers.
En la BricoLemon, la mayor ventaja de tener los drivers integrados es que no aseguramos de que están en su posición correcta, pero además están mejor refrigerados y para el usuario garantiza una puesta en marcha mucho más rápida.

Saludos!

**Comment by sl1pkn07** [comment]
lo sé, pero aun así, usuarios que son más expertos, que siempre andan toqueteado y cacharreando, y entre prueba y error se rompe los drivers, hacerle pagar 110/60 y algo de € cada vez en vez de 10€ (dependiendo modelo, montador, etc) es como un poco.....

saludos

**Comment by bricogeek** [comment]
Entiendo lo que dices, pero en ambos modelos de BricoLemon no está contemplado.
La gente con experiencia con este tipo de placas no suele romper nada ;)
Saludos!

**Comment by sl1pkn07** [comment]
O todo :)

son mas los novatos (por eso vuestra tasa de roturas) que los experimentados (que saben colocarlos) pero que los rompen por (mucho)uso (dile a un maker que está 24/7 que tiene que pagar 70/110 napos cada vez que se rompe uno)...

pero bueno. vosotros sabréis...

como veo que no cabe posibilidad, creo que se puede cerrar el hilo

saludos :)
