### ISSUE TITLE
Problemes with de order M600

### ISSUE THREAD

**Issue by bayerri93** [bricogeek/bricolemon#5]
Good morning,

My problem is with the order M600. When I active it to change the filament, the printer can not move to home positions. The X axes move correctly but the Y axes not, it moves to the oposite direction. When the extruder arribes at the end it fail som stepps and when it return to the position it's wrong position.

I don't know how to invert the movement of the Y axes at the M600.

Thank you very much

**Comment by bricogeek** [comment]
If you motor skips steps, maybe is another issue not related to filament change.
I may suggest you to recompile a fresh firmware from scratch and start again from there.

**Comment by bayerri93** [comment]
I don't think that because it fail stepps because try to find the end stop in the non correct corner. But thank you for the information
